name: Static Code Analysis
on:
  push:
    paths:
      - 'Gangs*/**'
      - '.github/workflows/inspect.yml'
  pull_request:
    paths:
      - 'Gangs*/**'
      - '.github/workflows/inspect.yml'

jobs:
  sample:
    name: .NET Code Analysis runner

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      # Run NuGet restore for the solution at repo root
      - name: Run NuGet restore
        run: dotnet restore
      
      # Run code analysis for the solution at repo root
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@main
        id: code-analysis
        with:
          build-breaking: true
          project: 'Gangs.sln'
          all-categories: all