name: Static Code Analysis

on:
  push:
    paths:
      - 'Gangs*/**'
      - '.github/workflows/inspect.yml'
  pull_request:
    paths:
      - 'Gangs*/**'
      - '.github/workflows/inspect.yml'

jobs:
  inspection:
    runs-on: ubuntu-latest
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./Gangs.sln
          dotnetVersion: ${{ steps.setup-dotnet.outputs.dotnet-version }}